### ISSUE TITLE
Unsplash assets source is not working anymore

### ISSUE THREAD

**Issue by valboivin** [jordannbeattie/craftcms-faker#2]
Hi! 
We've been using Unsplash as our assets source for a little while, but it recently stopped working. 
It seems like the url used to generate random images is not valid anymore. `https://source.unsplash.com/random` now returns a 503 error.

**Comment by jordannbeattie** [comment]
Hello! 
A few years back, Unsplash announced they were deprecating these URLs. 
They did say that all existing images would continue to work but that new images would not be accessible. Which is why it's been left as an option. 
A few others have been reporting issues with their API this week so I'm assuming it's an issue on their end and they intend to resolve it. 
The plugin provides Picsum as an alternative. If Unsplash announce that this is a permanent thing, that option will be removed from the plugin. 
Hope this helps.
